export enum DataTestIdsEnum {
  userAddress = 'userAddress',
  addressShard = 'addressShard',
  balance = 'balance',
  heroTag = 'heroTag',
  nftExplorerLink = 'nftExplorerLink',
  nftFormattedAmount = 'nftFormattedAmount',
  receiverLink = 'receiverLink',
  receiverShard = 'receiverShard',
  senderLink = 'senderLink',
  senderShard = 'senderShard',
  shardFromLink = 'shardFromLink',
  shardToLink = 'shardToLink',
  tokenExplorerLink = 'tokenExplorerLink',
  tokenFormattedAmount = 'tokenFormattedAmount',
  transactionHash = 'transactionHash',
  transactionLink = 'transactionLink',
  transactionMethod = 'transactionMethod',
  transactionReceiver = 'transactionReceiver',
  transactionSender = 'transactionSender',
  transactionValue = 'transactionValue'
}
