import '@/styles/globals.scss';
import { Layout, LayoutFallback } from '@/components/Layout';
import Head from 'next/head';
import Providers from '@/components/SdkDapp/providers';
import { Suspense } from 'react';

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <body>
        <Providers>
          <Suspense fallback={<LayoutFallback>{children}</LayoutFallback>}>
            <Layout>{children}</Layout>
          </Suspense>
        </Providers>
      </body>
    </html>
  );
}
