name: WDIO Tests

on: push
  
    # branches: [main]

jobs:
  E2E-RUN:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Start Devnet
        run: npm run start-devnet

      - name: Start WDIO
        run: npm run wdio-smoke
